version: "3"
services:
  # C++ Backend
  cpp_backend:
    build: .
    container_name: cpp_sensor_service
    ports:
      - "8080:8080"
    networks:
      - sensor_net

  # Frontend (Nginx)
  nginx:
    image: nginx:alpine
    container_name: web_dashboard
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cpp_backend
    networks:
      - sensor_net

  # SonarQube (Quality)
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_server
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sensor_net

networks:
  sensor_net:

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
