name: Build and Analyze C++ (Single Step Test)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ openjdk-17-jdk

      - name: Run SonarCloud C++ Scan
        uses: SonarSource/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: slav41k_cpp-sensor-project
          organization: slav41k
          args: >
            -Dsonar.cfamily.build-wrapper-output=build-wrapper-output 
            -Dsonar.cxx.file.suffixes=.cpp,.h
            -Dsonar.sources=.
            -Dsonar.exclusions=build/**,frontend/**

      - name: Compile Code (Required for Sonar)
        run: |
          mkdir build
          # Тут ми маємо запустити компіляцію, але без build-wrapper, щоб перевірити, чи знайдеться Action
          cmake -S . -B build
          cmake --build build/ --config Release

