name: Build and Analyze C++

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ openjdk-17-jdk

      # Цей Action автоматично встановлює build-wrapper та sonar-scanner
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: slav41k_cpp-sensor-project
          organization: slav41k
          args: >
            -Dsonar.cfamily.build-wrapper-output=build-wrapper-output 
            -Dsonar.cxx.file.suffixes=.cpp,.h
            -Dsonar.sources=.
            -Dsonar.exclusions=build/**,frontend/**

      # Скомпілюємо та обернемо код після сканера
      - name: Build and Wrap Code
        run: |
          /opt/sonarcloud/build-wrapper-linux-x86-64 --out-dir build-wrapper-output cmake -S . -B build

      - name: SonarCloud Final Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: slav41k_cpp-sensor-project
          organization: slav41k
          args: >
            -Dsonar.cfamily.build-wrapper-output=build-wrapper-output
            -Dsonar.cxx.file.suffixes=.cpp,.h
            -Dsonar.sources=.
            -Dsonar.exclusions=build/**,frontend/**
            -Dsonar.analysis.mode=preview

