name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Cache SonarCloud build-wrapper
        id: cache-build-wrapper
        uses: actions/cache@v3
        with:
          path: build-wrapper-output
          key: ${{ runner.os }}-build-wrapper-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-wrapper-cache-

      - name: Run build-wrapper and compile
        run: |
          mkdir build
          cmake -S . -B build
          /opt/sonarcloud/build-wrapper-linux-x86-64 --out-dir build-wrapper-output cmake --build build/ --config Release
        
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: slav41k_cpp-sensor-project
          organization: slav41k
          args: >
            -Dsonar.cfamily.build-wrapper-output=build-wrapper-output 
            -Dsonar.cxx.file.suffixes=.cpp,.h
            -Dsonar.sources=.
            -Dsonar.exclusions=build/**,frontend/**

